# Syntax reference:
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions

name: Build Docker

on:
  push:
    branches: [dev]
  pull_request:
    types: [opened, synchronize]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: |
        docker build . -t shadow --shm-size="1g"
        docker run --shm-size="1g" --rm shadow /src/ci/container_scripts/test.sh
